package app

import (
	"encoding/json"
	"html"
	"strings"
)

// uiStrings is the single place holding every user-visible string of the web
// UI. The pages carry no text of their own: HTML marks each spot with
// data-t="<key>" and the scripts look keys up through t()/fmt(). Swapping this
// map (or picking one of several) is all a future language switch needs.
//
// Keys are English identifiers; only the values are shown to the user.
// {name} placeholders are filled in by fmt() in the page scripts.
var uiStrings = map[string]string{ //nolint:gosec // G101: UI sentences; keys like error.conflict_secret name errors, not credentials
	// Navigation, page titles and the connection indicator.
	"nav.dashboard":           "Обзор",
	"nav.label":               "Разделы приложения",
	"nav.participants":        "Участники",
	"nav.settings":            "Настройки",
	"nav.menu":                "Меню",
	"theme.system":            "Тема: как в системе",
	"theme.light":             "Тема: светлая",
	"theme.dark":              "Тема: тёмная",
	"page.title.dashboard":    "agentlink — обзор",
	"page.title.participants": "agentlink — участники",
	"page.title.settings":     "agentlink — настройки",
	"link.on_many":            "на связи {online} из {total}",
	"link.off_count":          "нет связи: {online} из {total}",
	"link.unconfigured":       "не настроено",
	"link.app_not_running":    "agentlink не запущен",
	"link.no_code":            "нет кода связи — нажмите «Создать код» или впишите код, который вам дали",
	"link.no_peer":            "пока никого — добавьте адрес участника или дождитесь, пока вас найдут в локальной сети",
	"link.bad_code":           "код связи не совпадает с кодом участника по этому адресу — сверьте его",
	"link.same_name":          "у участника то же имя, что у вас, или это ваш собственный адрес — поменяйте имя или адрес",
	"link.wrong_peer":         "по добавленному адресу отвечает не тот участник — проверьте адрес",
	"link.removed":            "вас удалили из сети — попросите участника снова добавить ваш адрес",
	"link.name_taken":         "ваше имя уже занято другим участником — впишите другое имя и сохраните",
	"link.no_zerotier":        "ZeroTier не найден",
	"link.weak_code":          "старый короткий код связи, а agentlink доступен не только из локальной сети — нажмите «Создать код», сохраните и сообщите новый код участникам",
	"link.legacy_public":      "участник по добавленному адресу — старая версия agentlink, а она подключается только из локальной сети или ZeroTier — попросите его обновиться",

	// Tray menu (cmd/agentlink app.go, see tray.go).
	"tray.autostart":     "Запускать вместе с Windows",
	"tray.open_browser":  "Открыть в браузере",
	"tray.quit":          "Выход",
	"tray.update":        "доступна v{version}",
	"tray.update_retry":  "обновление после {time}",
	"tray.not_set_up":    "Не настроено — откройте настройки",
	"tray.error":         "Ошибка — откройте настройки",
	"tray.connected":     "{peer} — на связи",
	"tray.connected_n":   "На связи {online} из {total}",
	"tray.not_connected": "Нет связи — откройте настройки",
	"tray.lost":          "{peer} — нет связи",
	"tray.weak_code":     "слабый код — создайте новый",

	// Settings page.
	"settings.h1":                  "Настройки",
	"settings.identity.title":      "Профиль и подключение",
	"settings.handler.title":       "Ответы агента",
	"settings.application.title":   "Приложение",
	"settings.node.label":          "Ваше имя",
	"settings.node.hint":           "Как вас увидят другие участники, например morgott.",
	"settings.code.label":          "Код связи",
	"settings.code.hint":           "Вида XXXX-XXXX-XXXX, одинаковый у всех участников: один нажимает «Создать код» и сообщает его остальным. Старый код из 6 символов тоже работает, но его можно подобрать — замените его.",
	"settings.code.generate":       "Создать код",
	"settings.code.copy":           "Скопировать",
	"settings.code.generated":      "Код создан и сохранён — сообщите его участникам.",
	"settings.code.copied":         "Код скопирован.",
	"settings.code.copy_manual":    "Нажмите Ctrl+C, чтобы скопировать выделенный код.",
	"settings.my_addr":             "Ваш адрес для других участников: {addr}",
	"settings.my_addr.none":        "ZeroTier не найден — адрес выше из локальной сети. Для связи через интернет установите ZeroTier или дайте внешний адрес.",
	"settings.handler.label":       "Кто отвечает",
	"settings.handler.hint":        "Ручной режим оставляет ответ вам. При выборе агента входящий вопрос обрабатывается автоматически и только на чтение.",
	"settings.handler.context":     "Автоответчик видит текст как данные, а не как команду менять задачу или настройки. У него нет контекста живых сессий отправителя и получателя; готовый ответ отправляется обратно автоматически.",
	"settings.handler.none":        "Никто, отвечаю сам",
	"settings.handler.claude":      "Claude Code",
	"settings.handler.codex":       "Codex",
	"settings.agent.label":         "Программа агента",
	"settings.agent.pick":          "Указать…",
	"settings.agent.hint":          "Находится сама, как бы агент ни был установлен: приложение Codex или Claude, npm, установщик, winget, расширение VS Code. Если нет — нажмите «Указать…» и выберите codex.exe / codex.cmd или claude.exe.",
	"settings.agent.find":          "Найти заново",
	"settings.agent.finding":       "Ищу программу агента…",
	"settings.agent.not_found":     "Не найдена ни в одном известном месте — установите агента или нажмите «Указать…».",
	"settings.agent.from_path":     "Найдена в PATH: {path}",
	"settings.agent.from_setting":  "Указана: {path}",
	"settings.agent.gone":          "Не найдена: {path} — нажмите «Найти заново» или «Указать…».",
	"settings.agent.missing":       "Не найдена — нажмите «Найти заново» или «Указать…».",
	"settings.agent.found":         "Найден: {kind} — {path}",
	"agent_kind.path":              "PATH (путь поиска программ Windows)",
	"agent_kind.env":               "переменная CODEX_CLI_PATH",
	"agent_kind.standalone":        "установщик агента",
	"agent_kind.npm":               "пакет npm",
	"agent_kind.winget":            "пакет winget",
	"agent_kind.codex_app":         "приложение Codex",
	"agent_kind.claude_app":        "приложение Claude",
	"agent_kind.vscode":            "расширение VS Code",
	"agent_kind.vscode_insiders":   "расширение VS Code Insiders",
	"agent_kind.cursor":            "расширение Cursor",
	"agent_kind.windsurf":          "расширение Windsurf",
	"settings.agent.chosen":        "Выбрана программа: {path}.",
	"settings.agent.picking":       "Открыто окно выбора программы Windows — выберите программу агента в нём.",
	"settings.agent.pick_title":    "Выберите программу агента (codex или claude)",
	"settings.agent.filter":        "Программы (*.exe;*.cmd;*.bat)",
	"settings.agent.cancelled":     "Отменено — программа агента не изменилась.",
	"settings.work_dir.label":      "Рабочая папка",
	"settings.work_dir.hint":       "Папка проекта, в которой агент ищет ответ: нажмите «Выбрать…» и укажите её в окне Windows.",
	"settings.work_dir.pick":       "Выбрать…",
	"settings.work_dir.picking":    "Открыто окно выбора папки Windows — выберите папку в нём.",
	"settings.work_dir.pick_title": "Выберите рабочую папку",
	"settings.work_dir.chosen":     "Выбрана папка: {path}",
	"settings.work_dir.current":    "Сейчас: {path}",
	"settings.work_dir.empty":      "Папка не выбрана.",
	"settings.work_dir.cancelled":  "Отменено — папка не изменилась.",
	"settings.hooks.ok":            "Хуки: {agent} ✓ — живая сессия в этой папке узнаёт о новых сообщениях.",
	"settings.hooks.no_folder":     "Хуки: папка не найдена.",
	"settings.hooks.error":         "Хуки: не удалось записать настройки агента — подробности в agentlink.log.",
	"settings.hooks.codex":         "Codex запускает новые хуки только после проверки: один раз откройте /hooks в Codex в этой папке и разрешите их.",
	"settings.projects.title":      "Проекты",
	"settings.projects.hint":       "Вопрос на тему проекта агент решает в папке этого проекта, а не в рабочей папке. Тема сама добавится в «Общие темы».",
	"settings.projects.empty":      "Проектов нет — все вопросы агент решает в рабочей папке.",
	"settings.projects.area":       "Тема",
	"settings.projects.dir":        "Папка проекта",
	"settings.projects.warn":       "Любой участник с вашим кодом связи может через агента менять файлы и запускать команды в этих папках и в рабочей папке.",
	"settings.projects.add":        "Добавить проект",
	"settings.projects.remove":     "Удалить",
	"settings.advanced":            "Дополнительно",
	"settings.listen.label":        "Мой адрес",
	"settings.listen.hint":         "Пусто — все сети этого компьютера (ZeroTier, локальная, внешний адрес), порт 7420. Можно указать один IP, например адрес ZeroTier.",
	"settings.discovery.label":     "Искать участников в локальной сети и ZeroTier",
	"settings.discovery.hint":      "Раз в 5 секунд agentlink рассылает по сетям короткий сигнал (UDP, порт 7421) без кода связи; участники с тем же кодом подключаются друг к другу сами.",
	"settings.api.label":           "Адрес этой страницы",
	"settings.api.hint":            "Пусто — 127.0.0.1:7520; меняется после перезапуска agentlink.",
	"settings.areas.label":         "Общие темы",
	"settings.areas.hint":          "Через запятую: dev, design. Тогда сообщение можно послать на area:dev.",
	"settings.max_jobs.label":      "Сколько вопросов агент решает сразу",
	"settings.max_jobs.hint":       "От 1 до 4; пусто — 2. Остальные вопросы ждут в очереди и начинаются по порядку прихода.",
	"settings.autostart.label":     "Запускать agentlink при входе в Windows",
	"settings.auto_answer.label":   "Автоответ агентом, если сессия не открыта",
	"settings.auto_answer.hint":    "Выключено: сообщения ждут непрочитанными, пока в папке проекта не откроется сессия агента. Включено: если сессии нет, выбранный агент отвечает сам.",
	"settings.saving":              "Сохраняю…",
	"settings.saved":               "Сохранено.",

	// Dashboard and participants routes.
	"dashboard.h1":                 "Обзор",
	"dashboard.summary":            "На связи: {online} из {total}; сообщений: {messages}.",
	"dashboard.online":             "Участники",
	"dashboard.messages":           "Сообщения",
	"dashboard.active":             "Активные запросы",
	"dashboard.handler":            "Обработчик",
	"dashboard.recent":             "Последние разговоры",
	"dashboard.recent.empty":       "Пока нет разговоров.",
	"connection.reload":            "Обновить страницу",
	"participants.h1":              "Участники",
	"participants.empty":           "Пока нет участников.",
	"participants.online":          "на связи",
	"participants.lost":            "не в сети",
	"participants.seen":            "был на связи {when}",
	"participants.version":         "версия {version}",
	"participants.legacy":          "старая версия — не передаёт список участников",
	"participants.old_auth":        "старая версия — вход без защиты кода, только из локальной сети",
	"participants.addresses":       "адреса: {addresses}",
	"participants.counts":          "отправлено: {sent} · получено: {received} · всего: {total}",
	"participants.open_chat":       "Открыть переписку с участником {name}",
	"participants.remove":          "Удалить",
	"participants.remove_named":    "Удалить участника {name}",
	"participants.confirm":         "Удалить {name} из сети у всех участников? Вернуть можно, снова добавив его адрес.",
	"participants.removed":         "{name} удалён из сети.",
	"participants.add.legend":      "Добавить участника",
	"participants.add.label":       "Адрес участника",
	"participants.add.placeholder": "например, 10.147.20.9",
	"participants.add.hint":        "IP другого участника в ZeroTier, локальной сети или интернете; порт можно не писать.",
	"participants.add.submit":      "Добавить",
	"participants.add.added":       "Адрес {addr} добавлен — подключаюсь.",
	"participants.add.empty":       "Впишите IP участника.",

	// Updates: the settings page section and the tray menu.
	"update.legend":          "Обновления",
	"update.version":         "Версия {version}",
	"update.check":           "Проверить обновления",
	"update.apply":           "Обновить до {version}",
	"update.auto":            "Обновлять автоматически",
	"update.auto.hint":       "Раз в несколько часов agentlink проверяет выпуски на GitHub и сам ставит новую версию. Вопросы, над которыми работает агент, при перезапуске не прерываются.",
	"update.checking":        "Проверяю обновления…",
	"update.latest":          "У вас актуальная версия.",
	"update.available":       "Доступна версия {version}.",
	"update.none":            "На GitHub пока нет выпуска для этой системы.",
	"update.applying":        "Скачиваю и проверяю версию {version}…",
	"update.restarting":      "Версия {version} установлена — agentlink перезапускается, агент продолжает работу.",
	"update.disabled":        "Эта сборка без номера версии — обновление отключено.",
	"update.error.check":     "Не удалось проверить обновления — проверьте интернет; подробности в файле agentlink.log.",
	"update.error.apply":     "Не удалось установить обновление, осталась текущая версия — подробности в файле agentlink.log.",
	"update.error.ratelimit": "GitHub временно ограничил запросы, повторите после {time}.",
	"update.error.restart":   "Обновление установлено, но agentlink не перезапустился — закройте его и запустите снова.",

	// Errors: each one sentence saying what to do.
	"error.node":                   "Впишите ваше имя: буквы, цифры, «-» или «_», без пробелов.",
	"error.code":                   "Код связи — 12 латинских букв и цифр вида XXXX-XXXX-XXXX (или старый код из 6): нажмите «Создать код» или впишите код, который вам дали.",
	"error.peer_addr":              "Адрес участника не похож на IP — впишите, например, 10.147.20.9 или 10.147.20.9:7420.",
	"error.work_dir":               "Укажите существующую рабочую папку, в которой агент будет искать ответы, или выберите «Никто, отвечаю сам».",
	"error.handler":                "Выберите, кто отвечает: Claude Code, Codex или никто.",
	"error.handler_missing":        "Программа агента не найдена ни в одном известном месте — установите агента (приложение Codex, Claude Code, npm) или нажмите «Указать…» и выберите codex.exe / claude.exe.",
	"error.agent_path":             "«Программа агента» не найдена по указанному пути — нажмите «Указать…» и выберите её заново.",
	"error.listen_format":          "«Мой адрес» в «Дополнительно» должен быть IP этого компьютера, например 10.147.20.5, или пустым (все сети).",
	"error.listen":                 "Не удалось занять адрес {addr} — проверьте «Мой адрес» в «Дополнительно» или закройте другую копию agentlink.",
	"error.api":                    "«Адрес этой страницы» в «Дополнительно» должен быть вида 127.0.0.1:7520 или пустым.",
	"error.areas":                  "Общие темы в «Дополнительно» — слова из букв и цифр через запятую, например dev, design.",
	"error.projects":               "В «Проекты» у каждой строки должна быть тема — слово из букв и цифр — и полный путь к папке проекта.",
	"error.projects_twice":         "Одна тема в «Проекты» указана дважды — оставьте одну строку.",
	"error.peer_name":              "Имя участника в файле настроек — буквы, цифры, «-» или «_»; уберите его или исправьте.",
	"error.max_jobs":               "«Сколько вопросов агент решает сразу» в «Дополнительно» — целое число от 1 до 4 или пусто.",
	"error.peer_name_self":         "Имя одного из участников в файле настроек совпадает с вашим — поменяйте ваше имя.",
	"error.peer_name_twice":        "Одно имя участника записано в файле настроек дважды — оставьте его у одного адреса.",
	"error.not_configured":         "Сначала заполните настройки, потом добавляйте участников.",
	"error.remove_self":            "Себя удалить нельзя — удалить вас может другой участник.",
	"error.unknown_member":         "Такого участника нет — обновите страницу (F5).",
	"error.ambiguous_peer":         "Участников несколько — впишите в «Кому» имя: {peers}.",
	"error.start":                  "Настройки сохранены, но agentlink не запустился — подробности в файле agentlink.log рядом с настройками.",
	"error.save":                   "Не удалось записать настройки на диск — проверьте, что папка %APPDATA%\\agentlink доступна, и попробуйте снова.",
	"error.bad_request":            "Страница прислала неверные данные — обновите её (F5) и попробуйте снова.",
	"error.forbidden":              "Страница устарела — обновите её (F5).",
	"error.no_app":                 "agentlink не отвечает — запустите agentlink.exe и обновите страницу.",
	"error.internal":               "Что-то пошло не так — подробности в файле agentlink.log рядом с настройками.",
	"error.not_running":            "agentlink ещё не подключён — впишите код связи в настройках и сохраните.",
	"error.empty_body":             "Напишите текст сообщения.",
	"error.unknown_peer":           "Такой участник ещё ни разу не подключался — проверьте имя или дождитесь надписи «на связи» и отправьте снова.",
	"error.no_area_peer":           "На эту тему никто не подписан — проверьте «Общие темы» у участников.",
	"error.send":                   "Не удалось отправить сообщение — подробности в файле agentlink.log рядом с настройками.",
	"error.unknown_chat":           "Такой беседы нет — обновите страницу (F5).",
	"error.chat_closed":            "Беседа закрыта — чтобы продолжить тему, начните новую беседу.",
	"error.chat_legacy":            "Эту переписку без беседы нельзя закрыть — её можно убрать в архив.",
	"error.chat_unsupported":       "Беседу нельзя начать: {peers} сейчас не на связи или со старой версией agentlink — дождитесь подключения или обновления.",
	"error.chat_participants":      "Выберите хотя бы одного другого участника; ответ можно попросить только у участников беседы, не у себя.",
	"error.pick_busy":              "Окно выбора Windows уже открыто — закончите выбор в нём или закройте его.",
	"error.pick_unsupported":       "Окно выбора папки есть только в Windows — впишите путь к папке вручную.",
	"error.pick":                   "Не удалось открыть окно выбора папки — впишите путь вручную; подробности в файле agentlink.log.",
	"error.pick_agent_unsupported": "Окно выбора программы есть только в Windows — поставьте агента так, чтобы он был в PATH.",
	"error.pick_agent":             "Не удалось открыть окно выбора программы — подробности в файле agentlink.log.",
	// Inbox page: the chat list.
	"inbox.archive.show":     "Архив",
	"inbox.archive.hide":     "Все беседы",
	"inbox.badge.legacy":     "без беседы",
	"inbox.unread":           "Новое",
	"inbox.you":              "вы",
	"inbox.you.gen":          "вас",
	"inbox.toast.close":      "Закрыть уведомление",
	"inbox.author.own_agent": "ваш агент",
	"inbox.author.agent":     "агент {name}",
	"inbox.author.fyi":       "— вашему агенту для сведения",

	// Inbox page: the open chat.
	"inbox.empty_conversation":   "В беседе пока нет сообщений.",
	"inbox.back":                 "Назад",
	"inbox.close":                "Закрыть и в архив",
	"inbox.close.confirm":        "Закрыть беседу и убрать в архив? Беседа закроется у всех участников. Писать в неё больше будет нельзя, история останется.",
	"inbox.close.confirm_legacy": "Убрать переписку в архив? Она закроется у всех участников. Новое сообщение вернёт её из архива.",
	"inbox.close.confirm_old":    "Убрать переписку в архив? Она уберётся в архив только у вас: у участника старая версия.",
	"inbox.legacy_closed_note":   "Переписку убрал(а) в архив {name}, {when}.",
	"inbox.closed_note":          "Беседу закрыл(а) {name}, {when}. Чтобы продолжить тему, начните новую беседу.",
	"inbox.legacy_note":          "Переписка без беседы. Новое сообщение продолжит её в беседе с {name}.",
	"inbox.legacy_note_old":      "У {name} старая версия agentlink без бесед — сообщение уйдёт отдельным вопросом.",
	"inbox.new_with":             "Новая беседа с {names}",
	"inbox.participants.label":   "Участники беседы",
	"inbox.member.online":        "на связи",
	"inbox.member.away":          "не в сети",
	"inbox.member.old":           "старая версия agentlink — сообщения ждут обновления",
	"inbox.member.queued":        "не доставлено: {n}",
	"inbox.area":                 "тема: {area}",
	"inbox.older":                "Показать более ранние",
	"inbox.event.open":           "{name} начал(а) беседу",
	"inbox.event.close":          "{name} закрыл(а) беседу",
	"inbox.asks":                 "вопрос для {names}",
	"inbox.held":                 "Цепочка автоответов остановлена — чтобы продолжить, спросите сами.",
	"inbox.failed":               "Агент не смог ответить.",
	"inbox.hold.unknown":         "не отвечает автоматически — ждёт человека",
	"inbox.reply":                "Ответить",
	"inbox.tick.queued":          "не доставлено — ждёт отправки",
	"inbox.tick.delivered":       "доставлено, ещё не прочитано",
	"inbox.tick.read":            "прочитано",
	"inbox.tick.answered":        "ответил(а)",
	"inbox.info":                 "Подробности беседы",
	"inbox.info.sessions":        "Сессии агента на этом компьютере",
	"inbox.info.no_sessions":     "Открытых сессий нет.",
	"inbox.session.rewake":       "будит сессию сразу",
	"inbox.session.next_event":   "увидит при следующем действии",
	"inbox.member.old_short":     "старая версия",
	"inbox.reply_to":             "ответ на сообщение от {name}: {text}",

	// Inbox page: live activity of the participants' agents.
	"inbox.activity.label":           "Кто сейчас работает",
	"inbox.activity.queued":          "ждёт своей очереди",
	"inbox.activity.working":         "агент работает",
	"inbox.activity.waiting_session": "ждёт активности сессии",
	"inbox.activity.no_session":      "нет открытой сессии — сообщение ждёт",
	"inbox.activity.stale":           "нет связи",
	"inbox.presence.rewake":          "сессия открыта — прочитает сразу",
	"inbox.presence.next_event":      "сессия откроет при следующем действии",
	"inbox.presence.none":            "сессия не открыта — сообщение ждёт",
	"inbox.presence.worker":          "ответит агент-обработчик",
	"inbox.activity.type.thinking":   "думает",
	"inbox.activity.type.edit":       "правит",
	"inbox.activity.type.command":    "выполняет",
	"inbox.activity.type.read":       "читает",
	"inbox.activity.type.search":     "ищет",
	"inbox.activity.type.tool":       "инструмент",

	// Inbox page: the composer.
	"inbox.ask.label":        "Ответ нужен от",
	"inbox.ask.none":         "Никто не отмечен — сообщение уйдёт всем для сведения.",
	"inbox.body.label":       "Текст",
	"inbox.body.placeholder": "Напишите сообщение… Ctrl+Enter — отправить",
	"inbox.send":             "Отправить",
	"inbox.replying":         "Ответ на: {text}",
	"inbox.cancel_reply":     "Отменить ответ",

	// Inbox page: starting a chat.
	"inbox.new.title":        "Новая беседа",
	"inbox.new.participants": "С кем",
	"inbox.new.hint":         "Все участники видят все сообщения. Состав потом не меняется — для другого состава начните новую беседу.",
	"inbox.new.create":       "Начать беседу",
	"inbox.new.dismiss":      "Отмена",
	"inbox.new.no_members":   "Пока некого позвать — пригласите участников в проект.",

	// projects: server (Track A)
	"error.name":                      "Название проекта — от 1 до 80 символов, без управляющих символов.",
	"error.alias":                     "Своё название проекта — не длиннее 64 символов, без управляющих символов.",
	"error.dir":                       "Укажите полный путь к существующей папке или оставьте поле пустым.",
	"error.dir_taken":                 "Эта папка уже привязана к другому проекту — выберите другую.",
	"error.too_many_projects":         "Проектов уже 32 — выйдите из ненужного, чтобы добавить новый.",
	"error.invite":                    "Приглашение не распознано — скопируйте его целиком: ALP1.… или код вида XXXX-XXXX-XXXX.",
	"error.addr":                      "Адрес участника не похож на IP — впишите, например, 10.147.20.9 или 10.147.20.9:7420.",
	"error.conflict_secret":           "Этот проект уже есть здесь с другим приглашением — попросите участников прислать новое.",
	"error.legacy_exists":             "Код прежней сети уже задан — чтобы сменить его, сначала выйдите из «Прежней сети».",
	"error.not_found":                 "Такого проекта нет — обновите страницу (F5).",
	"error.legacy_rename":             "«Прежнюю сеть» переименовать нельзя.",
	"error.project_busy":              "Агент ещё выполняет запросы этого проекта — дождитесь окончания и повторите.",
	"error.legacy_invite_unavailable": "У прежней сети нет кода приглашения: она настроена длинным секретом.",
	"error.project_needs_folder":      "У проекта не выбрана папка — выберите её в меню проекта «Моя папка».",
	"error.folder_not_in_project":     "Эта папка не входит в папку проекта — запустите агента внутри папки проекта.",
	"error.project_binding":           "Запись одного из проектов в файле настроек повреждена — выйдите из проекта и присоединитесь снова по приглашению.",

	// projects: UI (Track B)
	"page.title.welcome":              "agentlink — начало",
	"page.title.project":              "agentlink — проект",
	"page.title.chat":                 "agentlink — чат",
	"projects.label":                  "Проекты",
	"projects.connecting":             "Подключение…",
	"projects.online":                 "на связи {online} из {total}",
	"projects.fold":                   "Чаты проекта {name}",
	"project.state.connecting":        "Подключаюсь к проекту — название появится, когда ответит кто-нибудь из участников.",
	"project.state.needs_folder":      "Папка проекта не выбрана: переписываться можно, но агент не отвечает. Выберите папку в меню проекта — «Моя папка».",
	"project.problem.unknown_project": "Участники не знают этот проект — возможно, приглашение устарело. Попросите новое.",
	"project.problem.wrong_project":   "По адресу участника отвечает другой проект — проверьте адрес.",
	"project.problem.auth":            "Приглашение не подходит к проекту участников — попросите новое.",
	"project.problem.name_taken":      "Ваше имя уже занято в этом проекте — смените имя в настройках.",
	"project.problem.removed":         "Вас удалили из проекта — попросите участников пригласить вас снова.",
	"welcome.h1":                      "Проектов пока нет",
	"welcome.hint":                    "У каждого проекта свои участники, чаты и папка. Создайте проект или присоединитесь по приглашению."}

// stringsAttr renders uiStrings as JSON escaped for an HTML attribute value.
func stringsAttr() string {
	data, err := json.Marshal(uiStrings)
	if err != nil { // a map[string]string always marshals
		return "{}"
	}
	return html.EscapeString(string(data))
}

// Text is msg for the tray menu.
func Text(key string, vars map[string]string) string { return msg(key, vars) }

// msg returns the text for key with {name} placeholders filled from vars, the
// server-side twin of fmt() in the page scripts.
func msg(key string, vars map[string]string) string {
	s, ok := uiStrings[key]
	if !ok {
		return uiStrings["error.internal"]
	}
	for k, v := range vars {
		s = strings.ReplaceAll(s, "{"+k+"}", v)
	}
	return s
}
